version: "3.4"

services:
  ennovate:
    image: ennovate
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
