FROM node:18-alpine
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json .
RUN npm install

# Copy the environment file and rename it to .env
COPY .env.development .env

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Expose the port and start the application
EXPOSE 8080
CMD [ "npm", "run", "preview" ]